name: super-linter # Название
# Определение триггера для запуска CI/CD
on: push # Триггер на push любого коммита в ветку
# Задачи к выполнению
jobs:
 super-lint: # задача
  name: lint code base # Название
  runs-on: ubuntu-latest # Сборка окружения ubuntu-latest
  steps: # Шаги задачи
    - name: Checkout code
      uses: actions/checkout@v2 # Переключение на текущую ветку
      
    - name: Super Linter  
      uses: docker://github/super-linter:v2.1.0 # Вызов Super Linter
      env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}

